name: Build Solr for CKAN

on:
  push:
    branches:
      - main

env:
  SOLR_VERSION: 6.6.6
  CKAN_VERSION: 2.9.4

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
    env:
      IMAGE_NAME: solr
      DOCKER_BUILDKIT: 1

    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t ${IMAGE_NAME} .

      - name: Login to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          IMAGE_TAG=${SOLR_VERSION}-ckan-${CKAN_VERSION}
          docker tag ${IMAGE_NAME} ${IMAGE_ID}:latest
          docker tag ${IMAGE_NAME} ${IMAGE_ID}:${IMAGE_TAG}
          docker push ${IMAGE_ID}:latest
          docker push ${IMAGE_ID}:${IMAGE_TAG}

  pushToECR:
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
    needs: build
    env:
      IMAGE_NAME: ghcr.io/georepublic/solr:latest
      AWS_REGION: ${{secrets.AWS_REGION}}
      ECR_BASE: ${{secrets.ECR_BASE}}
      ECR_REPO: ${{secrets.ECR_REPO}}

    steps:
      - uses: actions/checkout@v2

      - name: Get AWS Credential
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{secrets.ROLE_ARN}}
          role-session-name: ECRSession
          aws-region: ${{env.AWS_REGION}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Download Docker image
        run: docker pull ${IMAGE_NAME}
      
      - name: Push Docker Image on ECR
        run: |
          IMAGE_TAG=${SOLR_VERSION}-ckan-${CKAN_VERSION}
          docker tag ${IMAGE_NAME} ${ECR_BASE}/${ECR_REPO}:${IMAGE_TAG}
          docker push ${ECR_BASE}/${ECR_REPO}:${IMAGE_TAG}
